Changing update to upgrade
wolfienux@wolfie-macpro amb1s1-dotfile % brew update python3
Error: This command updates brew itself, and does not take formula names.
Use `brew upgrade python3` instead.